### ISSUE TITLE
Calculate target variable

### ISSUE THREAD

**Issue by christianLeomil** [aateg/tatu-re#29]

**Comment by christianLeomil** [comment]
Calculate target trying to optimise the next two weeks, with daily recomendation.
Percentual difference for the next 10 days, plot histogram.

**Comment by aateg** [comment]
Conflict resolved!
I also added the function in a new format, which I think is more simple. Check target.py

to test the code:
```python

from datetime import datetime
from tatu_re.utils import get_data
from tatu_re.target import calculate_target

start = datetime(2020,3,1)
end = datetime(2020,3,30)
df = get_data(start, end)

print(calculate_target(df["Close"]))
```
